Module Delegates
    Public Delegate Function ListOfEquipMentRequestDelegates() As List(Of PropsFields.eus_data_fields)
    Public Delegate Function ListOfProjectsDelegates() As List(Of PropsFields.project_maintenance_fields)
    Public Delegate Function ListOfWhItemProperNamesDelegates() As List(Of PropsFields.whItems_properName_fields)
    Public Delegate Function ListOfWhItemsDelegates() As List(Of PropsFields.whItems_props_fields)
    Public Delegate Function ListOfWhInchargeDelegates() As List(Of PropsFields.incharge_fields)
    Public Delegate Function ListOfListViewItemDelegates() As List(Of ListViewItem)
    Public Delegate Function ListOfDrItemsDelegates() As List(Of PropsFields.dr_props_fields)
    Public Delegate Function ListOfDrWsItemsDelegates() As List(Of PropsFields.dr_ws_props_fields)
    Public Delegate Function ListOfDrPoItemsDelegates() As List(Of PropsFields.dr_po_props_fields)
    Public Delegate Function ListOfOperatorDelegates() As List(Of PropsFields.operator_driver_props_fields)
    Public Delegate Function ListOfSupplierDelegates() As List(Of PropsFields.supplier_props_fields)
    Public Delegate Function ListOfEmployeesDelegates() As List(Of PropsFields.employee_props_fields)
    Public Delegate Function ListOfChargesInfoDelegates() As List(Of PropsFields.charges_info_props_fields)
    Public Delegate Function ListOfPurchaseOrderDelegates() As List(Of PropsFields.purchase_order_props_fields)
    Public Delegate Function ListOfWithdrawalDelegates() As List(Of PropsFields.withdrawal_props_fields)
    Public Delegate Function ListOfReceivingDelegates() As List(Of PropsFields.receiving_props_fields)
    Public Delegate Function ListOfRequisitionDelegates() As List(Of PropsFields.rs_props_fields)
    Public Delegate Function ListOfWhAreaStockpileDelegates() As List(Of PropsFields.whArea_stockpile_props_fields)
    Public Delegate Function ListOfEmployeeDataDelegates() As List(Of PropsFields.employee_props_fields)
    Public Delegate Function ListOfSmsUsersDelegates() As List(Of PropsFields.smsUsers_props_fields)
    Public Delegate Function ListOfWhInchargeNewDelegates() As List(Of PropsFields.inchargeNew_fields)
    Public Delegate Function ListOfWithdrawnItemsDelegates() As List(Of PropsFields.withdrawn_props_fields)
    Public Delegate Function ListOfPartiallyWithdrawnItemsDelegates() As List(Of PropsFields.partiallyWithdrawn_props_fields)
    Public Delegate Function ListOfPartiallyReleasedWithdrawnItemsDelegates() As List(Of PropsFields.partiallyReleasedWithdrawal_props_fields)

    Public Delegate Function ListOfRsDataDelegates() As List(Of PropsFields.rsdata_props_fields)
    Public Delegate Function ListOfMainRsDelegates() As List(Of PropsFields.main_rsdata_props_fields)
    Public Delegate Function ListOfEquipmentDelegates() As List(Of PropsFields.equipment_props_fields)
    Public Delegate Function ListOfAlLChargesDelegates() As List(Of PropsFields.AllCharges)
    Public Delegate Function ListOfAllAggPricesDelegates() As List(Of PropsFields.aggregatesPrices_props_fields)
    Public Delegate Function ListOfTirePositionDelegates() As List(Of PropsFields.tirePosition_props_fields)
    Public Delegate Function ListOfTireSerialNoDelegates() As List(Of PropsFields.tireSerial_props_fields)
    Public Delegate Function ListOfTireSerialNoViewDelegates() As List(Of PropsFields.tireSerialView_props_fields)
    Public Delegate Function ListOfKPIDelegates() As List(Of PropsFields.KPIprops_fields)
    Public Delegate Function ListOfMultipleKPIDelegates() As List(Of PropsFields.MultipleKPIprops_fields)
    Public Delegate Function ListOfTypeOfRequestDelegates() As List(Of PropsFields.TypeOfRequest)
    Public Delegate Function ListOfConsolidationAccount() As List(Of PropsFields.Consolidated_Account)
    Public Delegate Function ListOfRSForDrDelegates() As List(Of PropsFields.rs_for_dr_props_fields)
    Public Delegate Function ListOfWsForDrDelegates() As List(Of PropsFields.ws_for_dr_props_fields)
    Public Delegate Function ListOfDrForDrDelegates() As List(Of PropsFields.dr_for_dr_props_fields)
    Public Delegate Function ListOfPoForDrDelegates() As List(Of PropsFields.po_for_dr_props_fields)
    Public Delegate Function ListOfMultipleChargesDelegates() As List(Of PropsFields.MultipleCharges)
    Public Delegate Function ListOfQTODetailsDelegates() As List(Of PropsFields.QTO_details)
    Public Delegate Function ListOfCancelledTransactionDelegates() As List(Of PropsFields.CancelledTransaction)
    Public Delegate Function ListOfSearchByChargesDelegates() As List(Of PropsFields.byCharges)
    Public Delegate Function ListOfSearchByRequestedByDelegates() As List(Of PropsFields.byCharges)
    Public Delegate Function ListOfRsLocations() As List(Of String)


    Public Delegate Function prevStockCardBalanceDelegates() As Double
    Public Delegate Function stockcardRemBalanceDelegates() As Double


    Public Delegate Function functionDelegates()
    Public Delegate Sub subDelegates()
    Public Delegate Sub successFullyDoneDelegates()

End Module
